apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu
  labels:
    app: kubia
    rel: beta
spec:
  nodeSelector:
    gpu: "true"
  containers:
    - name: kotlin-kubia
      image: navkkrnair/kotlin-kubia:1.0
      ports:
        - containerPort: 8080
          protocol: TCP

