apiVersion: v1
kind: Pod
metadata:
  name: kubia
spec:
  containers:
    - name: kotlin-kubia
      image: navkkrnair/kotlin-kubia:1.0
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          protocol: TCP

